### ISSUE TITLE
Bug on headlessui Popover

### ISSUE THREAD

**Issue by M4RC0Sx** [tailwindlabs/tailwindui-issues#1625]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/application-ui/application-shells/stacked
- Component name: [Two-row navigation with overlap](https://tailwindui.com/components/application-ui/application-shells/stacked#component-d3429709d7862763cc93bbc60777c0fe)

**Describe the bug**
Using the exact component you have on the web on a NextJS 14.2.7 with React 18 app, if you spam click the toggle mobile navbar button which open and closes de Popover, it stops working. If I do it on your web it is not happening. Using @headlessui/react@2.1.2 becasue 2.1.3 totally breaks the popover open-close behavior.

**To Reproduce**
1. Make a small screen resolutoon to simulate a mobile phone and make the navbar collapse.
2. 2. Spam click the toggle popover menu button.

**Expected behavior**
You can spam click the button and the popover menu just opens and closes normally.

**Screenshots**
Not applicable

**Browser/Device (if applicable)**
 - OS: [e.g. iOS] Windows 11
 - Browser [e.g. chrome, safari] Firefox
 - Version [e.g. 22] 129.0.2

**Comment by reinink** [comment]
Hey @M4RC0Sx, thanks for bringing this to our attention. I'm going to close this issue in favor of https://github.com/tailwindlabs/headlessui/issues/3438 (I see you commented there too). Hopefully we can get this one fixed up quickly, but until then I recommend staying on v2.1.2 👍

**Comment by RobinMalfait** [comment]
Hey sorry about the regression!

This should be fixed, and is available in the next release ([2.1.4](https://github.com/tailwindlabs/headlessui/releases/tag/%40headlessui%2Freact%40v2.1.4)).

**Comment by M4RC0Sx** [comment]
> Hey sorry about the regression!
> 
> This should be fixed, and is available in the next release of Headless UI ([2.1.4](https://github.com/tailwindlabs/headlessui/releases/tag/%40headlessui%2Freact%40v2.1.4)).

Hi @RobinMalfait ! This is not fixed in 2.1.4, when you spam-click the button it stops working.

**Comment by RobinMalfait** [comment]
Hmm, can you verify a few things for me?

1. Verify that you are on the latest version `npm ls @headlessui/react` should give you the info. But you can also remove `node_modules`, `npm install` and then `npm install @headlessui/react@latest` to be sure.
2. Make sure you don't have any browser or node related caches going on. For example, if you are using Next.js, make sure to remove the `.next` folder.
3. Make sure you restart your dev server in case there are some in-memory caches that aren't flushed correctly. (This can happen in Next.js but I've also seen it happen in Vite related projects).


That said, this is the behavior I see:

1. On `2.1.3`, spamming the `PopoverButton` eventually (pretty quickly) breaks the Popover
2. On `2.1.4` spamming the `PopoverButton` doesn't break the Popover entirely. Do note that it's not an instant open / close due to the transition that is happening. But eventually when I stop spamming the button, it behaves as expected.

> [!CAUTION]
> Due to the spamming of the button, there will be flashing content in the video below. This video may potentially trigger seizures for people with photosensitive epilepsy.

https://github.com/user-attachments/assets/8dc73648-7016-4bb8-b802-9231b968a9f4

**Comment by M4RC0Sx** [comment]
Hi @RobinMalfait . Just tried it with all the steps you said and still getting same issue.

**Comment by RobinMalfait** [comment]
@M4RC0Sx can you share a (minimal) reproduction GitHub repo by any chance so that I can take a look?

**Comment by M4RC0Sx** [comment]
Just invited you to my repo. Latest changes with your steps are on develop branch. @RobinMalfait

**Comment by RobinMalfait** [comment]
I see the same correct behavior on your repo:

https://github.com/user-attachments/assets/40dacf81-bf45-4d99-ab46-65c21c486ab9


Assuming you did all the steps I mentioned:
0. stop `npm run dev` script
1. `rm -rf node_modules`
2. `rm -rf .next`
3. `npm install`
4. `npm install @headlessui/react@lateset`
5. `npm run dev`

Can you share which OS you are using, which browser and what version of that browser?

**Comment by M4RC0Sx** [comment]
Yes, all the steps done @RobinMalfait . I am using Windows 11 PRO 23H2 with WSL Ubuntu 20.04.6.
I am on Firefox 130.0 64 bits.

**Comment by RobinMalfait** [comment]
Hey @M4RC0Sx

I was able to reproduce this issue on Firefox. I wrote more about it here: #3452

Before publishing a new version, could you try with this insiders version:
```
npm install @headlessui/react@0.0.0-insiders.971ff6b
```

Let me know if this behaves the way you expect it to behave 👍

**Comment by M4RC0Sx** [comment]
Hi @RobinMalfait ! Thank you very much! Works like a charm with the insiders version!
